AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters: 
  ImageURL:
    Type: String
Globals:
  Function:
    Timeout: 360
    MemorySize: 512
Resources:
  IcebergMetricsLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageURL
      Policies: 
        - CloudWatchPutMetricPolicy: {}
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
        - AmazonEC2ContainerRegistryReadOnly
        - Statement:
          - Sid: GlueDataCatalogPolicy
            Effect: Allow
            Action:
            - glue:GetTable
            - glue:GetTableVersion
            - glue:GetTables
            - glue:GetDatabase
            - glue:GetDatabases
            - glue:SearchTables
            - glue:GetTableVersions
            - glue:GetPartitions
            - glue:ListSessions
            Resource: '*'
      Architectures:
        - x86_64
  PermissionForEventBridgeToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IcebergMetricsLambda
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/IcebergTablesUpdateRule*'
Outputs:
  IcebergMetricsLambda:
    Description: Lambda Function ARN
    Value: !GetAtt IcebergMetricsLambda.Arn